### ISSUE TITLE
Allow defining fully custom message

### ISSUE THREAD

**Issue by radeksimko** [Ilshidur/action-slack#12]
There's currently no way to suppress the first line which prints name of repository and other details which might not always be desired:

https://github.com/Ilshidur/action-slack/blob/4ab30779c772cac48ffe705d27a5a194e3d5ed78/entrypoint.js#L14

**Comment by Ilshidur** [comment]
I can create an env var that will prevent this, so you can fully customize your message.

Something like `SLACK_OVERRIDE_MESSAGE` as a boolean ? What do you think ? :smile:

**Comment by radeksimko** [comment]
I think the first option seems the most sensible as folks will be able to just stick with a single variable.

**Comment by Ilshidur** [comment]
Working on it ...

**Comment by Ilshidur** [comment]
Done.

You can override the message with the `SLACK_OVERRIDE_MESSAGE` environment variable :

* set it to `true` to remove the first line (which you don't want).
* set it to any other value to override the message in the `args` field.

Here's the commit : https://github.com/Ilshidur/action-slack/commit/2b459982ba311c3cdbdd69882502c2597a9c9625. Therefore, you can use the action with this name : `action-slack@2b45998`.

Thank you for raising this issue. I'd be happy to have some feedback ;-)
