### ISSUE TITLE
Recommendation to use commit hash is not valid anymore

### ISSUE THREAD

**Issue by trevor92** [Ilshidur/action-slack#179]
This text in the readme is no longer valid "Commit SHA-1 : uses: "Ilshidur/action-slack@689ad44" (→ link to the commits list : https://github.com/Ilshidur/action-slack/commits/master)"

Github Actions Error: Unable to resolve action `Ilshidur/action-slack@689ad44`, the provided ref `689ad44` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `689ad44a9c9092315abd286d0e3a9a74d31ab78a` instead.

**Comment by Ilshidur** [comment]
Hello Trevor.

Nice catch. Thank you for the notice.
I updated the README accordingly.

Feel free to reopen this issue if necessary.
