### ISSUE TITLE
Allow channel override

### ISSUE THREAD

**Issue by DannyBen** [Ilshidur/action-slack#2]
Would be nice if the channel can be set, perhaps using an environment variable?

**Comment by Ilshidur** [comment]
Agreed. Fixing this ...

**Comment by Ilshidur** [comment]
Done. The feature is available on this commit : `a44c528`.

You can override the webhook's channel using the `SLACK_CHANNEL` variable. More informations in the docs...

Feedback appreciated :-)

**Comment by DannyBen** [comment]
Wouldn't it make more sense to set `SLACK_CHANNEL` as an environment variable, and not as a secret?
As I understand, secrets are repository-wide, so there can be only one `SLACK_CHANNEL` variable throughout the repo, whereas environment variables are on a per-action basis, and both key and value are clearly visible and configurable.

**Comment by Ilshidur** [comment]
Exactly. This was a mistake on my end when redacting the docs. I fixed it.
