### ISSUE TITLE
multiple channel posts?

### ISSUE THREAD

**Issue by ms-carvajal** [Ilshidur/action-slack#216]
hey team there is a way to post in multiple channels?

**Comment by trevor92** [comment]
@ms-carvajal if this action does not support this, there is a way around this: 
1. setup a workflow in slack (if you have access), click arrow next to your org name, tools -> workflow builder, in choose a way to start this workflow, click webhook, url will be generated when you publish workflow
2. add this webhook in your github actions workflow and github repo as actions secret
- name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CUSTOM_PAYLOAD: '{ custom stuff here}'
        uses: Ilshidur/action-slack@master
3. In the workflow builder, you can specific which channels you want the workflow to post to 
4. Click add a step, send a message, click add, then you can specify which channel or person you want to send the message to

**Comment by ms-carvajal** [comment]
thanks, I figure out that the webhook always has a default channel and if the specified channel is not found, the request will be sent to the default channel. that's one way to solve it.
