### ISSUE TITLE
Populating Args with event info

### ISSUE THREAD

**Issue by tehpsalmist** [Ilshidur/action-slack#5]
Terribly sorry if this isn't a helpful question, but how do you get information from the action event to be used in the `args` message? For example, I'm subscribed to `issues` which is super broad, everything from a changed label to a comment on an issue. How can I configure my slack message to speak to the details of a given notification?

**Comment by Ilshidur** [comment]
Hello. I released a new version featuring this (**1.2.0**).

You can interpolate environment variables in the `args` message.
In your case, the proper way to show the event type is `{{ GITHUB_EVENT_NAME }}`.

*More informations in the README : https://github.com/Ilshidur/action-slack#arguments* :wink:
