### ISSUE TITLE
Publish docker image please!

### ISSUE THREAD

**Issue by mikeparker** [Ilshidur/action-slack#64]
Hi, i have to build this action using the dockerfile every run which takes 30 seconds. Can you just publish the docker image instead? It would speed everyones CI up by 20-25 seconds every run :)

Thanks!

**Comment by itsmelion** [comment]
I share you though,
i have been thinking about it since released v2.
need to study this better, but my guess was that not even Docker is needed.

The shell environment for github actions already includes Node.js,
and that may be enough to make the plugin work.

**Comment by Ilshidur** [comment]
Hello. As you guys can see in the linked PR above, you won't need Docker anymore, thanks to @itsmelion. :)

This PR greatly improved the run time, so I'll keep this issue closed because Docker won't be necessary. Let me know if you still need one.
